
version: '3.8'
networks:
  backend:
    driver:
      overlay
services:
  mysql:
    container_name: mysql_glpi
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    privileged: true
    deploy:
      replicas: 1
    volumes:
      - dbmysql:/var/lib/mysql
    environment:
      TZ : America/Manaus
      MYSQL_ROOT_PASSWORD: '10Sup25orte#17'
      MYSQL_DATABASE: glpi-db
      MYSQL_USER: glpi-db-user
      MYSQL_PASSWORD: '10Sup25orte#17'
    networks:
      - backend
  web:
    container_name: glpi-server
    build: ./web/.
    image: server_server:latest
    restart: always
    privileged: true
    deploy:
      replicas: 3
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - webdir:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
  phpmyadmin:
    container_name: glpi_phpmyadmin
    image: phpmyadmin:latest
    restart: always
    deploy:
      replicas: 1
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend
volumes:
  dbmysql: {}
  webdir: {}
