#!/bin/bash
echo "Atualizando a base e a estrutura do sistema operacional"
apt-get update -y && apt-get upgrade -y
echo ""
clear
echo "Baixando o docker"
curl -fsSL https://get.docker.com -o get.docker.sh
echo "" 
clear
echo "Instalando o docker"
sh get.docker.sh 
echo ""
clear
echo "Testando o docker" 
docker run hello-world
echo ""
clear
echo "Baixando o docker compose"
curl -SL https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64 -o /usr/bin/docker-compose
echo ""
clear
echo "Atribuindo permissao ao docker-compose"
chmod +x /usr/bin/docker-compose 
echo ""
clear
echo "Criando os diretorios" 
mkdir -p /home/darling/mysql/
mkdir -p /home/darling/glpi/
cd /home/darling/glpi/
echo ""
clear
echo "Fazendo download da aplicação do glpi 10.0.3"
wget https://github.com/glpi-project/glpi/releases/download/10.0.3/glpi-10.0.3.tgz
echo "Extraindo arquivos da Aplicação"
tar -xzvf /home/darling/glpi/glpi-10.0.3.tgz
mv /home/darling/glpi/glpi/* /home/darling/glpi/.
echo "Aplicando permissões necessarias"
chmod -R  777 /home/darling/glpi/config/
chmod -R  777 /home/darling/glpi/files/
chmod -R  777 /home/darling/glpi/marketing/
rm -rf /home/darling/glpi/glpi*
cd /home/darling/glpi-server/
"Criando os containers do GLPI - MYSQL - PHPADMIN"
docker-compose up -d
ehco "Insira o arquivo de backup de banco atualizado no diretorio: /home/darling/glpi-server com nome: glpi_backup.sql"
read confirma
echo "Confirme o diretorio do arquivo e nome do arquivo"
read confirma
echo ""
echo "Importando backup do glpi atualizado"
mysql -u root -p'Inf9ra5bas7e#hps-user' glpi-db-user < /home/darling/glpi-server/glpi_backup.sql 
echo ""
echo "Abra o navegador no Ip do Servidor"
echo "
