#!/bin/bash
echo "###################################################################"
echo "#                                                                 #"
echo "#      - Sistema de Instalação dp Glpi em Cluster Docker  -       #"
echo "#                                                                 #"
echo "#              Desenvolvido por CNSoltuions - LTDA                #"
echo "#                                                                 #"
echo "#         e-mail: reinaldoguedes@cnsolutions.com.br               #"
echo "#                                                                 #"
echo "###################################################################"
echo ""
echo " -* Preparando o Sistema para receber o Cluster GLPI *-"
echo ""
sleep 5
echo "Atualizando a base e a estrutura do sistema operacional"
apt-get update -y && apt-get upgrade -y
echo ""
echo "Instalando o docker"
curl -fsSL https://get.docker.com/ | sh
echo "" 
echo "Testando o docker" 
docker run hello-world
echo ""
echo "Instalando o docker compose"
sudo apt-get install docker-compose -y
echo ""
echo "Inicializando o swarm do docker"
docker swarm init
echo ""
echo "Criando os diretorios" 
mkdir -p ~/mysql/
mkdir -p ~/glpi/
echo ""
sleep 5
clear
echo " -* Iniciando as etapas da criação do cluster *-"
echo ""
echo "Fazendo download da aplicação do glpi 11.0.1"
wget https://github.com/glpi-project/glpi/releases/download/11.0.1/glpi-11.0.1.tgz
echo ""
echo "Extraindo arquivos da Aplicação"
tar -xzvf ~/glpi-server/glpi*.tgz
mv ~/glpi-server/glpi/* ~/glpi/.
echo ""
echo "Aplicando permissões necessarias"
chmod -R  777 ~/glpi/config/
chmod -R  777 ~/glpi/files/
chmod -R  777 ~/glpi/marketplace/
rm -rf ~/glpi-server/glpi*
cd ~/glpi-server/web/
echo ""
echo "Criando as imagens cluster GLPI - MYSQL - PHPADMIN"
docker-compose build 
echo ""
echo "Criando o Cluster GLPI"
docker stack deploy --compose-file ~/glpi-server/docker-compose.yml up
echo ""
echo "Acessar a pagina do IP do servidor e configurar a interface Web"
echo
